name: Move ON HOLD issue/PR to low priority column.
on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: ${{ secrets.TEAMNORDEN_ADMIN }}
        project-url: "https://github.com/TeamNorden/SWAT/projects/1"
        column-name: "On Deck"
        label-name: "priority"
        columns-to-ignore: "In Review,Ready to deploy,Done"