on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.ADMIN_ACCESS }}"
        project-url: "https://github.com/TeamNorden/SWAT/projects/1"
        column-name: "Needs Investigation"
        label-name: "needs triage"
        columns-to-ignore: "In Review,Ready to deploy,Done"