name: Move ON HOLD issue/PR to low priority column.
on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.TEAMNORDENADMIN }}"
        project-url: "https://github.com/TeamNorden/SWAT/projects/1"
        column-name: "Low Priority / Back-Burner"
        label-name: "low priority"' '